### ISSUE TITLE
Linked GotoWaypoint action is wrong

### ISSUE THREAD

**Issue by tompe17** [smarc-project/smarc_msgs#23]
In the the top documentation you get to

https://github.com/smarc-project/smarc_msgs/blob/interface/action/GotoWaypoint.action

when clicking on the link to the GotoWaypoint action.  The result and feedback is swapped in that file which fooled me since I trusted that it was correct... The master branch file seems to be correct.

**Comment by nilsbore** [comment]
Thank you! This was indeed wrong in the original version. Fixed now!
